### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by maximilliangreat** [Dreamsavior/portable-python-maker#1]
For example, unable to install telethon, (even if i set PATH before running), can not find built in module "tokenize"
`R:\ppython>pip3 install telethon
Collecting telethon
  Using cached Telethon-1.25.0-py3-none-any.whl (567 kB)
Collecting rsa
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting pyaes
  Using cached pyaes-1.6.1.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 11, in <module>
      ModuleNotFoundError: No module named 'tokenize'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

R:\ppython>pip install pip
Requirement already satisfied: pip in r:\ppython\lib\site-packages (22.2.2)`

**Comment by indraine** [comment]
Try change file `sitecustomize.py`.

Write 
```python
path = os.path.dirname(os.path.abspath(__file__))
```

instead of

```python
path = os.getcwd()
```

It should work

```python
# sitecustomize.py

import sys, os
sys.path = []
path = os.path.dirname(os.path.abspath(__file__))
sys.path.append('')
sys.path.append(os.path.join(path, "python310"))
sys.path.append(os.path.join(path, "Scripts"))
sys.path.append(path)
sys.path.append(os.path.join(path, "lib", "site-packages"))
```

**Comment by walkingsk** [comment]
I encountered similar errors with the same log structure when installing dependencies of [COMTool](https://github.com/Neutree/COMTool), it failed when building `pyperclip`.

I installed setuptools `python -m pip install setuptools` then the dependencies described in `requirements.txt` are successfully installed.
